version: '2'
services:
  MongoDB:
    container_name: ApiRestful-MongoDB
    image: mongo:latest
    volumes:
      - /data/db
    ports:
      - 28017:27017
    restart: always

  app:
    container_name: ApiRestful
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon --exec npm start
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/library
      - /home/app/library/node_modules
    links:
      - MongoDB:dbserver
